"""
icon.jpg → scripts/icon_b64.py 변환 스크립트
프로젝트 루트에서 실행: python scripts/encode_icon.py
"""
import base64
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "icon.jpg")
DST = os.path.join(ROOT, "scripts", "icon_b64.py")

if not os.path.exists(SRC):
    print("ERROR: icon.jpg not found in project root.")
    raise SystemExit(1)

with open(SRC, "rb") as f:
    data = base64.b64encode(f.read()).decode("ascii")

with open(DST, "w") as f:
    f.write("# Auto-generated by encode_icon.py — do not edit manually\n")
    f.write(f'ICON_B64 = "{data}"\n')

print(f"Done: {DST}")
